### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by asafnevo** [gaiterjones/amazon-alexa-php-hello-world-example#5]
Hi,

I was testing this project with my Alexa.

Through debug and when trying to test the skill, I keep getting the following error:

`(alexa),Request source IP address is not allowed.
`

I'm running the code from and EC2 instance located in Frankfurt.

Any idea what causing that?

**Comment by gaiterjones** [comment]
Hi,

validateAlexaRequest() is blocking this because the source IP address appears to be a private address - that could well be the case with an EC2 instance where the assigned server IP is taken from the private ip pool. You can disable this by commenting out the source ip address validation in

**AmazonDev/Alexa/ValidateAlexaRequest.php**

comment out the address check around about line 59

`//$this->validateSourceIPAddress();`


That should fix the error.

**Comment by asafnevo** [comment]
Thank you ill give it a try
